In [1]:
import random
random.seed(1)

In [2]:
import numpy as np

In [3]:
entradas = np.array([[0,0],[0,1],[1,0],[1,1]])
saidas = np.array([[0,0,0,1]]).T

In [4]:
entradas

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [5]:
saidas

array([[0],
       [0],
       [0],
       [1]])

In [6]:
# Pesos da rede neural

w1 = 2*np.random.random((2,4)) - 1
w2 = 2*np.random.random((4,1)) - 1

In [7]:
w1

array([[-0.26051873,  0.58712949, -0.62607309,  0.33214623],
       [ 0.97937203, -0.50803551,  0.48693369,  0.97354337]])

## 

In [8]:
w2

array([[-0.17238741],
       [ 0.53603403],
       [-0.96415517],
       [-0.89964831]])

In [9]:
# Treinamento da rede neural

for iteracao in range(10000):
    camada1 = 1/ (1 + np.exp(-(np.dot(entradas,w1))))
    camada2 = 1/ (1 + np.exp(-(np.dot(camada1,w2))))
    camada2_delta = (saidas-camada2)*(camada2*(1-camada2))
    camada1_delta = (camada2_delta.dot(w2.T))*(camada1*(1-camada1))
    w2 += camada1.T.dot(camada2_delta)
    w1 += entradas.T.dot(camada1_delta) 

In [10]:
camada2.round()

array([[0.],
       [0.],
       [0.],
       [1.]])

In [11]:
camada2

array([[0.00200895],
       [0.00959673],
       [0.00847029],
       [0.98782006]])