In [1]:
# Loops podem ser condicionais, sequenciais ou existir enquanto uma condição não for alcançada

In [7]:
var = "Eu vou aprender a programar"

In [8]:
for letras in var:
    print(letras)

E
u
 
v
o
u
 
a
p
r
e
n
d
e
r
 
a
 
p
r
o
g
r
a
m
a
r


In [9]:
var = ["Eu", "vou", "aprender", "a", "programar"]

In [10]:
for palavras in var:
    print(palavras)
print("Acabou")

Eu
vou
aprender
a
programar
Acabou


In [11]:
# Loop for com o if

dia_mes = list(range(1, 31))

print(dia_mes)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [12]:
for dias in dia_mes:
    if dias >= 15:
        print('Já passou do dia 15. Hoje é dia: ', dias)

Já passou do dia 15. Hoje é dia:  15
Já passou do dia 15. Hoje é dia:  16
Já passou do dia 15. Hoje é dia:  17
Já passou do dia 15. Hoje é dia:  18
Já passou do dia 15. Hoje é dia:  19
Já passou do dia 15. Hoje é dia:  20
Já passou do dia 15. Hoje é dia:  21
Já passou do dia 15. Hoje é dia:  22
Já passou do dia 15. Hoje é dia:  23
Já passou do dia 15. Hoje é dia:  24
Já passou do dia 15. Hoje é dia:  25
Já passou do dia 15. Hoje é dia:  26
Já passou do dia 15. Hoje é dia:  27
Já passou do dia 15. Hoje é dia:  28
Já passou do dia 15. Hoje é dia:  29
Já passou do dia 15. Hoje é dia:  30


In [13]:
import numpy as np

In [14]:
matriz_loop = np.array([[10, 11, 12],
                       [13, 14, 15], [16, 17, 18]])

matriz_loop

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [15]:
matriz_loop.shape[1]

3

In [17]:
for i in list(range(0,matriz_loop.shape[0])):
    for j in list(range(0,matriz_loop.shape[1])):
        print(matriz_loop[i][j])

10
11
12
13
14
15
16
17
18


In [18]:
# For serve também para fazer atribuições

anos = np.zeros((5,8))

anos

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
inicio = 2010

In [20]:
for i in list(range(0, anos.shape[0])):
    for j in list(range(0, anos.shape[1])):
        anos[i, j] = inicio
        inicio = inicio + 1

In [21]:
anos

array([[2010., 2011., 2012., 2013., 2014., 2015., 2016., 2017.],
       [2018., 2019., 2020., 2021., 2022., 2023., 2024., 2025.],
       [2026., 2027., 2028., 2029., 2030., 2031., 2032., 2033.],
       [2034., 2035., 2036., 2037., 2038., 2039., 2040., 2041.],
       [2042., 2043., 2044., 2045., 2046., 2047., 2048., 2049.]])

In [30]:
# Sequência de Fibonacci

n_elementos = 17

fibonacci = np.zeros(n_elementos)

fibonacci[1] = 1

for f in list(range(2, n_elementos)):
    fibonacci[f] = fibonacci[f-1] + fibonacci[f-2]
        
print(fibonacci)

[  0.   1.   1.   2.   3.   5.   8.  13.  21.  34.  55.  89. 144. 233.
 377. 610. 987.]
